# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-acm
  description: This component is responsible for requesting an ACM certificate for a domain and adding a CNAME record to the DNS zone to complete certificate validation
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





